// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxedijowsntlsynhkobi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4ZWRpam93c250bHN5bmhrb2JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDY3MDAsImV4cCI6MjA3MTc4MjcwMH0.8as0MChu5-kmWZgA9gyZFE8OfbBEnR0jwVS8GaqFous";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});